import {TSidebar} from "@/types/sidebar";

export const default_sidebar: TSidebar = [
  {
    id: 1,
    key: "1",
    name: "Default Dashboard",
    link: "/",
    icon: "material-symbols:dashboard-rounded",
    access_permission: true,
  },
  {
    id: 2,
    key: "2",
    name: "Default Settings",
    link: "/dashboard/settings",
    icon: "fluent:settings-24-filled",
    access_permission: true,
    submenu: [
      {
        parent_id: 2,
        name: "Default Sidebar",
        link: "/dashboard/default-sidebar",
        access_permission: true,
      },
    ],
  },
];

export const library_sidebar: TSidebar = [
  {
    id: 1,
    key: "Dashboard",
    name: "Dashboard",
    link: "/library",
    icon: "solar:pie-chart-2-bold",
    access_permission: true,
    submenu: [],
  },
  {
    id: 2,
    key: "Patron",
    name: "Patron",
    link: "/library/patrons",
    icon: "solar:user-circle-bold",
    access_permission: true,
    submenu: [
      {
        parent_id: 2,
        name: "Add Patron",
        link: "/library/patrons/create",
        access_permission: true,
      },
      {
        parent_id: 2,
        name: "Patron Request",
        link: "/library/patrons/request",
        access_permission: true,
      },
      {
        parent_id: 2,
        name: "Patron Active List",
        link: "/library/patrons",
        access_permission: true,
      },
      {
        parent_id: 2,
        name: "Security Money",
        link: "/library/patrons/security-money",
        access_permission: true,
      },
      {
        parent_id: 2,
        name: "Member Card",
        link: "/library/patrons/patroonship-card",
        access_permission: true,
      },
    ],
  },
  {
    id: 3,
    key: "Cataloging",
    name: "Cataloging",
    link: "/library/cataloging",
    icon: "solar:tuning-square-2-bold",
    access_permission: true,
    submenu: [
      {
        parent_id: 3,
        name: "Add Bibliography",
        link: "/library/cataloging/bibliographies/select-source",
        access_permission: true,
      },
      {
        parent_id: 3,
        name: "Biblio Records",
        link: "/library/cataloging/bibliographies",
        access_permission: true,
      },
      {
        parent_id: 3,
        name: "Label Creator",
        link: "/library/cataloging/label-creator",
        access_permission: true,
      },
      {
        parent_id: 3,
        name: "Rebind",
        link: "/library/cataloging/rebinds",
        access_permission: true,
      },
    ],
  },
  {
    id: 4,
    key: "Circulation",
    name: "Circulation",
    link: "/library/circulation",
    icon: "solar:repeat-one-minimalistic-bold",
    access_permission: true,
    submenu: [
      {
        parent_id: 4,
        name: "Check Out",
        link: "/library/circulation/check-out",
        access_permission: true,
      },
      {
        parent_id: 4,
        name: "Check In",
        link: "/library/circulation/check-in",
        access_permission: true,
      },
      {
        parent_id: 4,
        name: "Fine",
        link: "/library/circulation/fine",
        access_permission: true,
      },
      {
        parent_id: 4,
        name: "Reserved",
        link: "/library/circulation/reserved",
        access_permission: true,
      },
      {
        parent_id: 4,
        name: "Renew",
        link: "/library/circulation/renew",
        access_permission: true,
      },
      {
        parent_id: 4,
        name: "Circulation Policy",
        link: "/library/circulation/circulation-policy",
        access_permission: false,
      },
    ],
  },
  {
    id: 5,
    key: "Inter Circulation",
    name: "Int-Circulation",
    link: "/library/inter-circulation",
    icon: "solar:video-frame-replace-outline",
    access_permission: true,
    submenu: [
      {
        parent_id: 5,
        name: "Incoming",
        link: "/library/inter-circulation/incoming",
        access_permission: true,
      },
      {
        parent_id: 5,
        name: "Transfer",
        link: "/library/inter-circulation/transfer",
        access_permission: true,
      },
      {
        parent_id: 5,
        name: "History",
        link: "/library/inter-circulation/history",
        access_permission: true,
      },
    ],
  },

  {
    id: 6,
    key: "DAP",
    name: "DAP",
    link: "/library/dap",
    icon: "solar:user-bold",
    access_permission: true,
    submenu: [
      {
        parent_id: 6,
        name: "Demand",
        link: "/library/dap/demand",
        access_permission: true,
      },
      {
        parent_id: 6,
        name: "Pending Request",
        link: "/library/dap/pending-request",
        access_permission: true,
      },
      {
        parent_id: 6,
        name: "Approved List",
        link: "/library/dap/approved-list",
        access_permission: true,
      },
      {
        parent_id: 6,
        name: "Requisition",
        link: "/library/dap/requisition",
        access_permission: true,
      },
      {
        parent_id: 6,
        name: "Price Quotation",
        link: "/library/dap/price-quotation",
        access_permission: true,
      },
      // {
      //   parent_id: 6,
      //   name: "MIR Report",
      //   link: "/library/dap/mir-report",
      //   access_permission: false,
      // },
      {
        parent_id: 6,
        name: "Vendor",
        link: "/library/dap/vendor",
        access_permission: true,
      },
      // {
      //   parent_id: 7,
      //   name: "Approve Layer",
      //   link: "/library/dap/approve-layer",
      //   access_permission: false,
      // },
    ],
  },
  {
    id: 7,
    key: "Damage & Lost",
    name: "Damage Lost",
    link: "/library/damage-lost-weed",
    icon: "solar:danger-bold",
    access_permission: true,
    submenu: [
      {
        parent_id: 7,
        name: "Waste by User",
        link: "/library/damage-lost-weed/waste-by-user",
        access_permission: true,
      },
      {
        parent_id: 7,
        name: "Waste by Library",
        link: "/library/damage-lost-weed/waste-by-library",
        access_permission: true,
      },
      {
        parent_id: 7,
        name: "Discharge Books",
        link: "/library/damage-lost-weed/discharge-books",
        access_permission: true,
      },
    ],
  },
  {
    id: 8,
    key: "Library Clearance",
    name: "Clearance",
    link: "/library/library-clearance",
    icon: "solar:users-group-rounded-bold-duotone",
    access_permission: true,
    submenu: [
      {
        parent_id: 8,
        name: "Security Money Withdraw",
        link: "/library/library-clearance/security-money-withdraw",
        access_permission: true,
      },
      {
        parent_id: 8,
        name: "Discharge Patron",
        link: "/library/library-clearance/discharge-patron",
        access_permission: true,
      },
    ],
  },
  {
    id: 9,
    key: "Advance Search",
    name: "Advance Search",
    link: "/library/advance-search",
    icon: "solar:card-search-bold",
    access_permission: true,
    submenu: [],
  },

  {
    id: 10,
    key: "OPAC",
    name: "OPAC",
    link: "/library/opac",
    icon: "solar:global-bold",
    access_permission: true,
    submenu: [
      {
        parent_id: 10,
        name: "Notice",
        link: "/library/opac/notice",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "Event",
        link: "/library/opac/events",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "Footer",
        link: "/library/opac/footer",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "Contact Us",
        link: "/library/opac/contact-us",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "About Us",
        link: "/library/opac/about-us",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "Menu Setup with Page Build",
        link: "/library/opac/menu-setup-with-page-build",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "New Arrivals",
        link: "/library/opac/new-arrivals",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "Popular Book",
        link: "/library/opac/popular-book",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "Services",
        link: "/library/opac/services",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "E-Resources",
        link: "/library/opac/e-resourses",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "FAQ",
        link: "/library/opac/faq",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "Newspaper",
        link: "/library/opac/newspaper",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "Scrolling Text",
        link: "/library/opac/scrolling-text",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "Reference Links",
        link: "/library/opac/reference-links",
        access_permission: true,
      },
      {
        parent_id: 10,
        name: "Reviews",
        link: "/library/opac/student-reviews",
        access_permission: true,
      },
    ],
  },
  {
    id: 11,
    key: "Reports",
    name: "Reports",
    link: "/library/reports",
    icon: "solar:document-medicine-bold",
    access_permission: true,
    submenu: [],
  },
  {
    id: 11,
    key: "Settings",
    name: "Settings",
    link: "/library/settings",
    icon: "solar:settings-minimalistic-bold",
    access_permission: true,
    submenu: [
      {
        parent_id: 11,
        name: "Master Files",
        link: "/library/settings/authorized-values",
        access_permission: true,
      },
      {
        parent_id: 11,
        name: "Item Fields",
        link: "/library/settings/item-fields",
        access_permission: true,
      },
      {
        parent_id: 11,
        name: "Library",
        link: "/library/settings/libraries",
        access_permission: true,
      },
      {
        parent_id: 11,
        name: "Patron Category",
        link: "/library/settings/patron-categories",
        access_permission: true,
      },
      {
        parent_id: 11,
        name: "Patron Form Configuration",
        link: "/library/settings/patron-form-configuration",
        access_permission: true,
      },
      {
        parent_id: 11,
        name: "Basic Setup",
        link: "/library/settings/basic-setup",
        access_permission: true,
      },
      {
        parent_id: 11,
        name: "Framework Setup",
        link: "/library/settings/framework-setup",
        access_permission: true,
      },
      {
        parent_id: 11,
        name: "Upload Local Cover Image",
        link: "/library/settings/upload-local-cover-image",
        access_permission: true,
      },
      {
        parent_id: 11,
        name: "Policy Setup",
        link: "/library/settings/policy-setup",
        access_permission: true,
      },
      {
        parent_id: 11,
        name: "Clearance Template Setup",
        link: "/library/settings/clearance-template-setup",
        access_permission: true,
      },
      {
        parent_id: 11,
        name: "Exports / Import",
        link: "/library/settings/exports-import",
        access_permission: true,
      },
      {
        parent_id: 11,
        name: "System Log",
        link: "/library/settings/system-log",
        access_permission: true,
      },
      {
        parent_id: 11,
        name: "Role Permission",
        link: "/library/settings/role-permission",
        access_permission: true,
      },
    ],
  },
  {
    id: 12,
    key: "Database Backup",
    name: "DB Backup",
    link: "/library/database-backup",
    icon: "solar:database-bold-duotone",
    access_permission: true,
    submenu: [
      {
        parent_id: 12,
        name: "Setup Backup",
        link: "/library/database-backup/setup-backup",
        access_permission: true,
      },
      {
        parent_id: 12,
        name: "Manual Backup",
        link: "/library/database-backup/manual-backup",
        access_permission: true,
      },
    ],
  },
];

export const user_sidebar: TSidebar = [
  {
    id: 1,
    key: "sidebar_key_user_1",
    name: "Dashboard",
    link: "/user",
    icon: "ic:round-dashboard",
    access_permission: true,
    submenu: [],
  },
  {
    id: 4,
    key: "sidebar_key_user_4",
    name: "Users Manage",
    link: "/user/users-manage",
    icon: "solar:user-bold",
    access_permission: true,
    submenu: [
      {
        parent_id: 4,
        name: "Add User",
        link: "/user/users-manage/create",
        access_permission: true,
      },
      {
        parent_id: 4,
        name: "User List",
        link: "/user/users-manage",
        access_permission: true,
      },
      {
        parent_id: 4,
        name: "Salutation",
        link: "/user/users-manage/salutation",
        access_permission: true,
      },
    ],
  },
  {
    id: 3,
    key: "sidebar_key_user_3",
    name: "Permission",
    link: "/user/permission",
    icon: "icon-park-outline:permissions",
    access_permission: true,
    submenu: [],
  },

  {
    id: 2,
    key: "sidebar_key_user_11",
    name: "Settings",
    link: "/user/settings",
    icon: "ic:outline-settings",
    access_permission: true,
    submenu: [
      {
        parent_id: 2,
        name: "Role",
        link: "/user/settings/role",
        access_permission: true,
      },
      {
        parent_id: 2,
        name: "Login Access",
        link: "/user/settings/login-access",
        access_permission: true,
      },
    ],
  },
];
export const ebook_sidebar: TSidebar = [
  {
    id: 1,
    key: "Dashboard",
    name: "Dashboard",
    link: "/e-book",
    icon: "ic:round-dashboard",
    access_permission: true,
    submenu: [],
  },

  {
    id: 2,
    key: "E-Book Add",
    name: "Add Item",
    link: "/e-book/item-list/create",
    icon: "icon-park-outline:permissions",
    access_permission: true,
    submenu: [],
  },

  {
    id: 3,
    key: "E-Book List",
    name: "Item List",
    link: "/e-book/item-list",
    icon: "solar:user-bold",
    access_permission: true,
    submenu: [],
  },
  {
    id: 4,
    key: "Master-File",
    name: "Master File",
    link: "/e-book/master-file",
    icon: "ic:outline-settings",
    access_permission: true,
    submenu: [],
  },
  {
    id: 5,
    key: "User List",
    name: "User List",
    link: "/e-book/users",
    icon: "solar:user-circle-bold",
    access_permission: true,
    submenu: [],
  },
  {
    id: 6,
    key: "Report",
    name: "Report",
    link: "/e-book/report",
    icon: "solar:document-medicine-bold",
    access_permission: true,
    submenu: [],
  },

  {
    id: 7,
    key: "Settings",
    name: "Settings",
    link: "/e-book/settings",
    icon: "ic:outline-settings",
    access_permission: true,
    submenu: [
      {
        parent_id: 6,
        name: " Item Type",
        link: "/e-book/settings/item-type",
        access_permission: true,
      },
      {
        parent_id: 6,
        name: " Role & Permission",
        link: "/e-book/settings/role-permission",
        access_permission: true,
      },
    ],
  },
];
