export enum InputFieldsEnum {
  TEXT = "text",
  NUMBER = "number",
  DATE = "date",
  TIME = "time",
  CHECKBOX = "checkbox",
  RADIO = "radio",
  SELECT = "select",
  MULTI_SELECT = "multi-select",
  TEXTAREA = "textarea",
  FILE = "file",
  IMAGE = "image",
  DATE_TIME = "date-time",
  EMAIL = "email",
  PHONE = "phone",
  URL = "url",
  PASSWORD = "password",
  CURRENCY = "currency",
  CREDIT_CARD = "credit-card",
  SEARCH = "search",
  HIDDEN = "hidden",
  COLOR = "color",
  DATETIME_LOCAL = "datetime-local",
  WEEK = "week",
  MONTH = "month",
  TIME_ZONE = "time-zone",
  WEEK_DAY = "week-day",
}